// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_DockModel.cpp"
#include "UVLADIE3JM/moc_DockSettings.cpp"
#include "UVLADIE3JM/moc_PanelRegistry.cpp"
#include "UVLADIE3JM/moc_WindowModel.cpp"
